import os
print("Setting environment variables...")
# These should match GitHub Actions env names or local needs
os.environ["APP_NAME"] = os.getenv("APP_NAME", "MyApp")
os.environ["SECRET_KEY"] = os.getenv("SECRET_KEY", "dummykey")
os.environ["ALGORITHM"] = os.getenv("ALGORITHM", "HS256")
os.environ["DEFAULT_PASSWORD"] = os.getenv("DEFAULT_PASSWORD", "default")
os.environ["ENVIRONMENT"] = os.getenv("ENVIRONMENT", "LOCAL")
os.environ["DATABASE_URL"] = os.getenv("DATABASE_URL", "sqlite:///test.db")
os.environ["BASE_URL"] = os.getenv("BASE_URL", "http://localhost:5173")
os.environ["PINNACLE_API_KEY"] = os.getenv("PINNACLE_API_KEY", "default_api_key")
os.environ["PINNACLE_SENDER_ID"] = os.getenv("PINNACLE_SENDER ID", "default_sender")
os.environ["PINNACLE_DLT_ENTITY_ID"] = os.getenv("PINNACLE_DLT_ENTITY_ID", "default_entity_id")
os.environ["PINNACLE_OTP_DLT_TEMPLATE_ID"] = os.getenv("PINNACLE_OTP_DLT_TEMPLATE_ID", "default_template_id")
os.environ["PINNACLE_API_URL"] = os.getenv("PINNACLE_API_URL", "default_api_url")
os.environ["SBI_MERCHANT_ID"] = os.getenv("SBI_MERCHANT_ID", "default_merchand_id")
os.environ["SBI_AGGREGATOR_ID"] = os.getenv("SBI_AGGREGATOR_ID", "default_aggregator_id")
os.environ["SBI_ENCRYPTION_KEY"] = os.getenv("SBI_ENCRYPTION_KEY", "default_sncryption_id")
os.environ["SBI_API_ENDPOINT"] = os.getenv("SBI_API_ENDPOINT", "default_api_endpoint")
os.environ["SBI_DOUBLE_VALIDATION_URL"] = os.getenv("SBI_DOUBLE_VALIDATION_URL", "default_double_validation_url")
